CREATE TABLE IF NOT EXISTS product (
	id BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품ID',
	name VARCHAR(500) NOT NULL COMMENT '상품명',
	price INT NOT NULL COMMENT '가격(원)',
	stock INT NOT NULL COMMENT '재고',
	is_active TINYINT NOT NULL DEFAULT 1 COMMENT '활성화여부',
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	created_user_id BIGINT NOT NULL COMMENT '등록자',
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
	updated_user_id BIGINT NOT NULL COMMENT '수정자',
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user (
	id BIGINT NOT NULL AUTO_INCREMENT COMMENT '유저ID',
	email VARCHAR(100) NOT NULL COMMENT '이메일',
	name VARCHAR(50) NOT NULL COMMENT '이름',
	password VARCHAR(500) NOT NULL COMMENT '패스워드',
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX user_email_index ON USER(email);

CREATE TABLE IF NOT EXISTS user_roles (
	user_id BIGINT NOT NULL COMMENT '유저ID',
	roles VARCHAR(50) NOT NULL COMMENT '유저 권한',
	PRIMARY KEY (user_id, roles)
);